### ISSUE TITLE
Doesn't compile whe retrieved

### ISSUE THREAD

**Issue by DamianReeves** [nvivo/Even#3]
The source code doesn't compile as is... the HintPaths in the Even.csproj point to some `modahub2\admin-api` directory.

**Comment by nvivo** [comment]
Wow, my fault. =) Thanks for the notice @DamianReeves

**Comment by DamianReeves** [comment]
No problem. Is there a timetable for having an example of what an actual SqlStore for this will look like. I'm thinking I might want to tackle an Oracle version for my own use?

**Comment by nvivo** [comment]
Hey, sorry for the delay. Quite busy lately...

There is already an implementation that works fine [here](https://github.com/nvivo/Even/blob/master/Src/Even/Persistence/BaseSqlStore.cs) that you can follow. It shouldn't change much. You can also start fresh by implementing from `IEventStore` and using a table structure similar this one [here](https://github.com/nvivo/Even/blob/master/Src/Even/Persistence/MySqlStore.cs#L19-L45).

There are test cases you can extend for oracle, just look at the [examples for mysql and sql server](https://github.com/nvivo/Even/tree/master/Src/Even.Tests/Persistence). The tests are store-agnostic, so you can just extend and add some settings to connect to a test database and it should work.

For some background on why the stores are commented out, there are 2 things: 

1) I moved to using an `Stream` object to represent the stream id. It was using strings everywhere, and it was fine for regular streams, but projections were creating a hex string of the hash to use the API, and that was quite weird. I wanted streams to be represented in the same way everywhere, so I got rid of that.  The sql stores has to be changed and I'd need to cleanup some stuff. In order to getting it to compile, I just commented out the stores to fix that later.

2) I want to have a simpler base class with less optimizations that is easier to be extended for other stores. The current implementation is heavily optimized for MySql but it turned out to be quite complicated to optimize for other stores. I plan to have a simpler version that at least requires less changes even if it's slower by default. Optimizations can be done later.

If you need any extra info, let me know.

**Comment by DamianReeves** [comment]
Thanks for this. This project looks very promising. Can't wait for the first NuGet package.
